---
layout: post
toc: true
title: ML, Exercise Data
description: exercise machine learning 
courses: { csp: {week: 25} }
type: ccc
---

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exercise Pulse Prediction</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-color: #E6E6FA;
            padding-top: 50px;
        }
        form {
            margin: auto;
            width: 50%;
        }
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin: 5px 0;
            border-radius: 5px;
            border: 1px solid #734f96;
        }
        button {
            padding: 10px 20px;
            border: none;
            border-radius: 20px;
            background-color: #734f96;
            color: white;
            cursor: pointer;
        }
        #prediction {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>Exercise Pulse Prediction</h1>
    <form id="predictionForm">
        <input type="text" id="id" placeholder="ID">
        <input type="text" id="diet" placeholder="Diet">
        <input type="text" id="time" placeholder="Time">
        <input type="text" id="kind" placeholder="Kind">
        <button type="button" onclick="predict()">Predict Pulse</button>
    </form>
    <div id="prediction"></div>

<script>
        function predict() {
            const id = document.getElementById('id').value;
            const diet = document.getElementById('diet').value;
            const time = document.getElementById('time').value;
            const kind = document.getElementById('kind').value;

            // Send data to backend API
            fetch('http://localhost:5000/predict', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({id: id, diet: diet, time: time, kind: kind})
            })
            .then(response => response.json())
            .then(data => {
                // Display prediction
                document.getElementById('prediction').innerText = `Predicted Pulse: ${data.prediction}`;
            })
            .catch(error => console.error('Error:', error));
        }
    </script>
</body>
</html>

In [1]:
import seaborn as sns
# Load the titanic dataset
exercise_data = sns.load_dataset('exercise')
print("Exercise Data")
print(exercise_data.columns) # titanic data set
display(exercise_data[['id', 'diet' ,'pulse' ,'time','kind']])

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

Exercise Data
Index(['Unnamed: 0', 'id', 'diet', 'pulse', 'time', 'kind'], dtype='object')

    id     diet  pulse    time     kind
0    1  low fat     85   1 min     rest
1    1  low fat     85  15 min     rest
2    1  low fat     88  30 min     rest
3    2  low fat     90   1 min     rest
4    2  low fat     92  15 min     rest
..  ..      ...    ...     ...      ...
85  29   no fat    135  15 min  running
86  29   no fat    130  30 min  running
87  30   no fat     99   1 min  running
88  30   no fat    111  15 min  running
89  30   no fat    150  30 min  running

[90 rows x 5 columns]

In [7]:
import seaborn as sns
import pandas as pd
# Preprocess the data
from sklearn.preprocessing import OneHotEncoder

# Preprocessing steps
td = exercise_data.copy()  # Make a copy to avoid modifying the original data
td.dropna(inplace=True) # drop rows with at least one missing value
td['id'] = td['id'].astype('category').cat.codes # Encoding id as categorical
td['diet'] = td['diet'].astype('category').cat.codes # Encoding diet as categorical
td['time'] = td['time'].astype('category').cat.codes # Encoding time as categorical
td['kind'] = td['kind'].astype('category').cat.codes # Encoding kind as categorical

print(td.columns)
display(td)

Index(['Unnamed: 0', 'id', 'diet', 'pulse', 'time', 'kind'], dtype='object')

    Unnamed: 0  id  diet  pulse  time  kind
0            0   0     1      4     0     0
1            1   0     1      4     1     0
2            2   0     1      7     2     0
3            3   1     1      9     0     0
4            4   1     1     11     1     0
..         ...  ..   ...    ...   ...   ...
85          85  28     0     35     1     2
86          86  28     0     33     2     2
87          87  29     0     18     0     2
88          88  29     0     27     1     2
89          89  29     0     38     2     2

[90 rows x 6 columns]

In [18]:
# Median
# Calculate the median of the category codes for the 'kind' column
print("id:")
median_id_cat_code= td['id'].median()
print(median_id_cat_code)
print("diet:")
median_diet_cat_code= td['id'].median()
print(median_diet_cat_code)
print("pulse:")
median_pulse_cat_code= td['id'].median()
print(median_pulse_cat_code)
print("time:")
median_time_cat_code= td['id'].median()
print(median_time_cat_code)
print("kind:")
median_kind_cat_code= td['id'].median()
print(median_kind_cat_code)

id:
14.5
diet:
14.5
pulse:
14.5
time:
14.5
kind:
14.5

In [19]:
# Mean

# Median
# Calculate the mean of the category codes for the 'kind' column
print("id:")
mean_id_cat_code= td['id'].mean()
print(mean_id_cat_code)
print("diet:")
mean_diet_cat_code= td['id'].mean()
print(mean_diet_cat_code)
print("pulse:")
mean_pulse_cat_code= td['id'].mean()
print(mean_pulse_cat_code)
print("time:")
mean_time_cat_code= td['id'].mean()
print(mean_time_cat_code)
print("kind:")
mean_kind_cat_code= td['id'].mean()
print(mean_kind_cat_code)

id:
14.5
diet:
14.5
pulse:
14.5
time:
14.5
kind:
14.5

In [17]:
# Select numerical columns
numeric_columns = exercise_data.select_dtypes(include=['number'])
print("Maximums score")
print(numeric_columns[exercise_data['pulse'] == 110].max())
print()
print("Minimums score")
print(numeric_columns[exercise_data['pulse'] == 83].min())

Maximums score
Unnamed: 0     73
id             25
pulse         110
dtype: int64

Minimums score
Unnamed: 0    11
id             4
pulse         83
dtype: int64

In [23]:
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Load the exercise dataset using Seaborn
exercise_data = sns.load_dataset('exercise')

# Display the columns and a sample of the dataset
print("Exercise Data Columns:")
print(exercise_data.columns)
print("\nSample of the Exercise Data:")
print(exercise_data[['id', 'diet', 'pulse', 'time', 'kind']].head())

# Split the data into features (X) and target (y)
X = exercise_data[['id', 'diet', 'time', 'kind']]
y = exercise_data['pulse']

# Perform one-hot encoding for the categorical columns
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['diet', 'time', 'kind'])], remainder='passthrough')
X_encoded = ct.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.3, random_state=42)

# Train a linear regression model
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Print the model coefficients
print("Model Coefficients:")
print(regressor.coef_)

# Print the model intercept
print("Model Intercept:")
print(regressor.intercept_)

# Evaluate the model
y_pred = regressor.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Exercise Data Columns:
Index(['Unnamed: 0', 'id', 'diet', 'pulse', 'time', 'kind'], dtype='object')

Sample of the Exercise Data:
   id     diet  pulse    time  kind
0   1  low fat     85   1 min  rest
1   1  low fat     85  15 min  rest
2   1  low fat     88  30 min  rest
3   2  low fat     90   1 min  rest
4   2  low fat     92  15 min  rest
Model Coefficients:
[  2.06438483  -2.06438483  -6.79921446   1.24599372   5.55322074
  16.66418351 -11.13404753  -5.53013598   2.47242722]
Model Intercept:
61.02286544466105
Mean Squared Error: 78.17109502813513

In [29]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Load the exercise dataset
exercise_data = pd.read_csv("../exercise.csv")

# Define a new passenger
passenger = pd.DataFrame({
    'id': [101],  # Choose an ID that does not exist in the original dataset
    'diet': ['low fat'],
    'time': ['1 min'],
    'kind': ['rest']
})

# Preprocess the new passenger data
new_passenger = pd.get_dummies(passenger, columns=['diet', 'time', 'kind'])

# Combine the new passenger's data with the original dataset
combined_data = pd.concat([exercise_data, new_passenger], ignore_index=True)

# Split the data into features (X) and target (y)
X = combined_data[['id', 'diet', 'time', 'kind']]
y = combined_data['pulse']

# Perform one-hot encoding for the categorical columns
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['diet', 'time', 'kind'])], remainder='passthrough')
X_encoded = ct.fit_transform(X)

# Train a linear regression model
regressor = LinearRegression()
regressor.fit(X_encoded[:-1], y[:-1])  # Exclude the last row which is the new passenger's data

# Predict the pulse rate for the new passenger
pulse_prediction = regressor.predict(X_encoded[-1:])  # Predict for the last row which is the new passenger's data

# Round off the predicted pulse rate to two decimal places
rounded_pulse_prediction = round(pulse_prediction[0], 2)

# Print the predicted pulse rate
print('Predicted Pulse Rate:', rounded_pulse_prediction)

Predicted Pulse Rate: 243.63